name: Build and Publish NuGet Package

on:
    workflow_dispatch:
    release:
        types: [published]

defaults:
    run:
        shell: pwsh
        working-directory: ./src

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release

            - name: Pack NuGet package
              run: dotnet pack --configuration Release --no-build --output ./artifacts

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Test
              run: dotnet test --configuration Release --no-build

    publish:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        needs: [build, test]

        steps:

            - name: Push to nuget.org
              run: |
                foreach($file in (Get-ChildItem ./artifacts -Recurse -Include *.nupkg)) {
                    dotnet nuget push $file --api-key "${{ secrets.MICROCQRS_NUGET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
                }