name: Build and Publish NuGet Package

on:
    workflow_dispatch:
    release:
        types: [published]

defaults:
    run:
        shell: pwsh
env:
  NuGetDirectory: ${{ github.workspace}}/artifacts
  
jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore ./src

            - name: Build
              run: dotnet build ./src --configuration Release

            - name: Pack NuGet package
              run: dotnet pack ./src --configuration Release --no-build --output ${{ env.NuGetDirectory }}
              
            - name: save artifacts
              uses: actions/upload-artifact@v3
              with:
                name: nuget
                if-no-files-found: error
                retention-days: 7
                path: ${{ env.NuGetDirectory }}/*.nupkg

            - name: Test
              run: dotnet test ./src --configuration Release --no-build

    publish:
        # if: github.event_name == 'release'
        runs-on: ubuntu-latest
        needs: build_and_test

        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: nuget
                  path: ${{ env.NuGetDirectory }}

            - name: Push to nuget.org
              run: |
                foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
                    dotnet nuget push $file --api-key "${{ secrets.MICROCQRS_NUGET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
                }
